stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - pack
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  only:
    - develop
    - main
  script:
    - echo "Skip Build"
    
build-dockerhub-cr-image-job:
  stage: pack
  environment: develop
  before_script:
    - "echo $SIT_CI_REGISTRY_PASSWORD | docker login -u $SIT_CI_REGISTRY_USER --password-stdin "
  only:
    - develop
  script:
    - echo "build docker image..."
    - export REPO=dockerhub && export TARGET=amd64 && make push
    - echo "Docker image successfully built."

build-azure-cr-image-job:
  stage: pack
  environment: main
  before_script:
    - "echo $ACR_CI_REGISTRY_PASSWORD | docker login -u $ACR_CI_REGISTRY_USER --password-stdin $ACR_CI_REGISTRY"
  only:
    - main
  script:
    - echo "build docker image..."
    - export REPO=acr && export TARGET=amd64 && make push
    - echo "Docker image successfully built."


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  only:
    - develop
    - main
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - echo "Code coverage is 90%"

deploy-sit-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: develop
  only:
    - develop
  script:
    - echo "Deploying application..."
    - kubectl rollout restart -n vnmt01 deployment d2c-app
    - echo "Application successfully deployed."
