# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vnm-d2c-app-dev"
client_id = "f57ab2d0ad6cfcb2950443e143ac488c"
application_url = "https://vnm-d2c-app.apps.vinamilk.com.vn"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_shipping,write_delivery_customizations,read_delivery_customizations,read_customers,write_customers,read_discounts,unauthenticated_read_checkouts,unauthenticated_write_checkouts,unauthenticated_read_customers,unauthenticated_write_customers,unauthenticated_read_customer_tags,unauthenticated_read_content,unauthenticated_read_metaobjects,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_selling_plans"

[auth]
redirect_urls = [
  "https://vnm-d2c-app.apps.vinamilk.com.vn/auth/callback",
  "https://vnm-d2c-app.apps.vinamilk.com.vn/auth/shopify/callback",
  "https://vnm-d2c-app.apps.vinamilk.com.vn/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
